---
roles:
  - name: nginxinc.nginx
  - name: jdauphant.ssl-certs
  # - name: galaxyproject.self_signed_certs

collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 6.2.0
